import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@app/globals.css";
import { login } from "./core/services/Auth";
import { ClientProviders } from "./ClientProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container my-2">
          <button
            className="bg-gray-500 text-white p-1 px-4 float-end"
            onClick={login}
          >
            Login
          </button>
          <ClientProviders>{children}</ClientProviders>
        </div>
      </body>
    </html>
  );
}
